### ISSUE TITLE
不知道为啥没法运行，已经求助过gpt了

### ISSUE THREAD

**Issue by cocoILoveYoucoco** [singularity-s0/fudan_sports_autoreserve#13]
Traceback (most recent call last):
  File "C:\Users\A\Desktop\fudan_sports_autoreserve-master\main.py", line 1, in <module>
    import apis
  File "C:\Users\A\Desktop\fudan_sports_autoreserve-master\apis.py", line 4, in <module>
    import easyocr
ModuleNotFoundError: No module named 'easyocr'

**Comment by singularity-s0** [comment]
该模块不再使用，现已删除，请更新后重试。
