### ISSUE TITLE
预约报错

### ISSUE THREAD

**Issue by durianmangosteen** [singularity-s0/fudan_sports_autoreserve#8]
请问一下这种报错如何处理呢
INFO				Begin Captcha Recognition
INFO				Captcha Result: 8256, Confidence: 0.9999922513961792
VITAL				Reservation Failed
Traceback (most recent call last):
  File "C:\Users\z\PycharmProjects\pythonProject\reserve stadium.py", line 26, in <module>
    apis.reserve(logged_in_session, service_id, SERVICE_CATEGORY, DATE, TIME)
  File "C:\Users\z\PycharmProjects\pythonProject\apis\__init__.py", line 180, in reserve
    raise Exception("Reservation Failed")
Exception: Reservation Failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\z\PycharmProjects\pythonProject\reserve stadium.py", line 36, in <module>
    connection.login(YOUR_EMAIL, EMAIL_PASSWORD)
  File "C:\Users\z\AppData\Local\Programs\Python\Python39\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Users\z\AppData\Local\Programs\Python\Python39\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Users\z\AppData\Local\Programs\Python\Python39\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.3 Authentication unsuccessful [PS1PR03CA0016.apcprd03.prod.outlook.com 2023-07-25T09:58:47.420Z 08DB8C869BB40696]')

Process finished with exit code 1

**Comment by singularity-s0** [comment]
当前日志没有记录任何有价值的信息，请将日志等级设置为DEBUG再尝试

**Comment by durianmangosteen** [comment]
已经解决了，感谢
